version: "3"

services:
  db:
    image: "mysql"
    container_name: db
    networks:
      - messnet
    environment:
      - MYSQL_ROOT_PASSWORD=root
  messenger:
    build: .
    image: messenger
    container_name: messenger
    networks:
      - messnet
    ports:
    - 8000:8000

networks:
  messnet:
    name: messnet
    driver: bridge